photo_libraryPhoto Gallery (click to zoom)
City Center Business Hotel photo 1
City Center Business Hotel photo 2<?php
// php/api/seed.php – Seeds all real listing data into the database
// Run once: php php/api/seed.php  OR  visit /php/api/seed.php?secret=csnexplore_seed
require_once __DIR__ . '/../config.php';

$secret = $_GET['secret'] ?? $argv[1] ?? '';
if (php_sapi_name() !== 'cli' && $secret !== 'csnexplore_seed') {
    http_response_code(403); die('Forbidden');
}

$db = getDB()->getConnection();

// ── Helper ────────────────────────────────────────────────────────────────────
function seedTable($db, $table, $rows) {
    $existing = $db->query("SELECT COUNT(*) FROM $table")->fetchColumn();
    if ($existing > 0) { echo "SKIP $table (already has $existing rows)\n"; return; }
    $count = 0;
    foreach ($rows as $row) {
        $cols = implode(',', array_keys($row));
        $ph   = implode(',', array_map(fn($k) => ":$k", array_keys($row)));
        $stmt = $db->prepare("INSERT INTO $table ($cols) VALUES ($ph)");
        $params = [];
        foreach ($row as $k => $v) $params[":$k"] = $v;
        $stmt->execute($params);
        $count++;
    }
    echo "SEEDED $table: $count rows\n";
}

// ── STAYS ─────────────────────────────────────────────────────────────────────
$stays = [
  ['name'=>'Hotel Renaissance Aurangabad','type'=>'Luxury Hotel','location'=>'CIDCO N-12, Chhatrapati Sambhajinagar','description'=>'A premium full-service hotel offering luxurious rooms, multi-cuisine dining, swimming pool, and world-class amenities in the heart of the city.','price_per_night'=>4500,'rating'=>8.9,'reviews'=>312,'badge'=>'Bestseller','amenities'=>json_encode(['WiFi','Pool','Restaurant','Parking','AC']),'image'=>'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80','is_active'=>1,'display_order'=>1],
  ['name'=>'Panchakki Garden Stay','type'=>'Heritage Hotel','location'=>'Near Panchakki, Chhatrapati Sambhajinagar','description'=>'Experience heritage hospitality near the iconic Panchakki water-mill. Peaceful, well-maintained rooms with garden views.','price_per_night'=>2200,'rating'=>8.2,'reviews'=>184,'badge'=>'','amenities'=>json_encode(['WiFi','Garden','Restaurant','Parking']),'image'=>'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80','is_active'=>1,'display_order'=>2],
  ['name'=>'Budget Inn CSN','type'=>'Budget Hotel','location'=>'Osmanpura, Chhatrapati Sambhajinagar','description'=>'Clean, affordable rooms with all essential amenities. Ideal for solo travelers and backpackers.','price_per_night'=>900,'rating'=>7.4,'reviews'=>97,'badge'=>'','amenities'=>json_encode(['WiFi','AC','Parking']),'image'=>'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80','is_active'=>1,'display_order'=>3],
  ['name'=>'Grishneshwar Pilgrim Lodge','type'=>'Guesthouse','location'=>'Khuldabad, near Ellora','description'=>'Simple and peaceful stay near Grishneshwar Jyotirlinga temple. Ideal for pilgrims and heritage tourists.','price_per_night'=>750,'rating'=>7.8,'reviews'=>56,'badge'=>'','amenities'=>json_encode(['WiFi','Parking']),'image'=>'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80','is_active'=>1,'display_order'=>4],
  ['name'=>'Standard Comfort Rooms','type'=>'Hotel','location'=>'Jalna Road, Chhatrapati Sambhajinagar','description'=>'Comfortable standard rooms with 24-hour room service, free Wi-Fi, and breakfast included.','price_per_night'=>1600,'rating'=>8.0,'reviews'=>142,'badge'=>'Popular','amenities'=>json_encode(['WiFi','Restaurant','AC','Parking']),'image'=>'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&q=80','is_active'=>1,'display_order'=>5],
  ['name'=>'Ellora Heritage Resort','type'=>'Resort','location'=>'Near Ellora Caves, Chhatrapati Sambhajinagar','description'=>'Luxury resort with stunning views of Ellora hills. Features spa, outdoor pool, and fine dining restaurant.','price_per_night'=>5500,'rating'=>9.1,'reviews'=>245,'badge'=>'Luxury','amenities'=>json_encode(['WiFi','Pool','Spa','Restaurant','Gym','Parking','AC']),'image'=>'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80','is_active'=>1,'display_order'=>6],
  ['name'=>'City Center Business Hotel','type'=>'Business Hotel','location'=>'Jalna Road, Chhatrapati Sambhajinagar','description'=>'Modern business hotel with conference rooms, high-speed internet, and executive lounge.','price_per_night'=>3200,'rating'=>8.4,'reviews'=>178,'badge'=>'','amenities'=>json_encode(['WiFi','Conference Room','Restaurant','Parking','AC']),'image'=>'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80','is_active'=>1,'display_order'=>7],
  ['name'=>'Ajanta View Homestay','type'=>'Homestay','location'=>'Fardapur, Near Ajanta','description'=>'Cozy homestay with local hospitality. Perfect base for exploring Ajanta Caves.','price_per_night'=>1200,'rating'=>8.6,'reviews'=>89,'badge'=>'Homestay','amenities'=>json_encode(['WiFi','Home-cooked meals','Parking']),'image'=>'https://images.unsplash.com/photo-1586611292717-f828b167408c?w=800&q=80','is_active'=>1,'display_order'=>8],
  ['name'=>'Airport Transit Hotel','type'=>'Transit Hotel','location'=>'Near Airport, Chhatrapati Sambhajinagar','description'=>'Convenient hotel near airport with 24-hour check-in. Perfect for early morning flights.','price_per_night'=>1800,'rating'=>7.9,'reviews'=>134,'badge'=>'','amenities'=>json_encode(['WiFi','24hr Check-in','Restaurant','Parking','AC']),'image'=>'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800&q=80','is_active'=>1,'display_order'=>9],
  ['name'=>"Backpacker's Den Hostel",'type'=>'Hostel','location'=>'Osmanpura, Chhatrapati Sambhajinagar','description'=>'Budget-friendly hostel with dormitory and private rooms. Common area and kitchen facilities.','price_per_night'=>500,'rating'=>8.2,'reviews'=>267,'badge'=>'Budget Friendly','amenities'=>json_encode(['WiFi','Common Kitchen','Lounge']),'image'=>'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800&q=80','is_active'=>1,'display_order'=>10],
];
seedTable($db, 'stays', $stays);

// ── CARS ──────────────────────────────────────────────────────────────────────
$cars = [
  ['name'=>'Mahindra Scorpio N','type'=>'SUV','location'=>'Chhatrapati Sambhajinagar','description'=>'7-seater powerful SUV, perfect for group trips and outstation travel. Self-drive or with driver.','price_per_day'=>3500,'rating'=>8.8,'reviews'=>76,'badge'=>'Popular','fuel_type'=>'Diesel','transmission'=>'Manual','seats'=>7,'image'=>'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800&q=80','is_active'=>1,'display_order'=>1],
  ['name'=>'Honda City ZX','type'=>'Sedan','location'=>'Chhatrapati Sambhajinagar','description'=>'Elegant sedan for business or leisure travel. Comfortable and fuel-efficient.','price_per_day'=>2200,'rating'=>8.5,'reviews'=>54,'badge'=>'','fuel_type'=>'Petrol','transmission'=>'Automatic','seats'=>5,'image'=>'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80','is_active'=>1,'display_order'=>2],
  ['name'=>'Suzuki Swift Dzire','type'=>'Sedan','location'=>'Chhatrapati Sambhajinagar','description'=>'Compact, comfortable sedan great for city commutes and short outstation trips.','price_per_day'=>1800,'rating'=>8.1,'reviews'=>89,'badge'=>'','fuel_type'=>'Petrol','transmission'=>'Manual','seats'=>5,'image'=>'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80','is_active'=>1,'display_order'=>3],
  ['name'=>'Toyota Fortuner','type'=>'Premium SUV','location'=>'Chhatrapati Sambhajinagar','description'=>'Top-of-the-line premium SUV with full comfort for long-distance and luxury travel.','price_per_day'=>6500,'rating'=>9.2,'reviews'=>43,'badge'=>'Luxury','fuel_type'=>'Diesel','transmission'=>'Automatic','seats'=>7,'image'=>'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80','is_active'=>1,'display_order'=>4],
  ['name'=>'Maruti Ertiga','type'=>'MUV','location'=>'Chhatrapati Sambhajinagar','description'=>'Spacious 7-seater MUV perfect for family trips. Comfortable and economical.','price_per_day'=>2500,'rating'=>8.3,'reviews'=>112,'badge'=>'Family Favorite','fuel_type'=>'Petrol','transmission'=>'Manual','seats'=>7,'image'=>'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&q=80','is_active'=>1,'display_order'=>5],
  ['name'=>'Hyundai Creta','type'=>'Compact SUV','location'=>'Chhatrapati Sambhajinagar','description'=>'Stylish compact SUV with modern features and comfortable interiors.','price_per_day'=>3200,'rating'=>8.7,'reviews'=>98,'badge'=>'Trending','fuel_type'=>'Diesel','transmission'=>'Automatic','seats'=>5,'image'=>'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&q=80','is_active'=>1,'display_order'=>6],
  ['name'=>'Tata Nexon','type'=>'Compact SUV','location'=>'Chhatrapati Sambhajinagar','description'=>'Compact SUV with excellent safety features and powerful performance.','price_per_day'=>2800,'rating'=>8.4,'reviews'=>87,'badge'=>'','fuel_type'=>'Diesel','transmission'=>'Manual','seats'=>5,'image'=>'https://images.unsplash.com/photo-1502161254066-6c74afbf07aa?w=800&q=80','is_active'=>1,'display_order'=>7],
  ['name'=>'Innova Crysta','type'=>'MUV','location'=>'Chhatrapati Sambhajinagar','description'=>'Premium 7-seater MUV with captain seats. Perfect for long journeys.','price_per_day'=>4500,'rating'=>9.0,'reviews'=>156,'badge'=>'Premium','fuel_type'=>'Diesel','transmission'=>'Automatic','seats'=>7,'image'=>'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80','is_active'=>1,'display_order'=>8],
  ['name'=>'Maruti Alto','type'=>'Hatchback','location'=>'Chhatrapati Sambhajinagar','description'=>'Economical hatchback perfect for city driving. Great fuel efficiency.','price_per_day'=>1200,'rating'=>7.8,'reviews'=>145,'badge'=>'Budget','fuel_type'=>'Petrol','transmission'=>'Manual','seats'=>4,'image'=>'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&q=80','is_active'=>1,'display_order'=>9],
  ['name'=>'Kia Seltos','type'=>'Compact SUV','location'=>'Chhatrapati Sambhajinagar','description'=>'Feature-packed compact SUV with connected car technology and premium interiors.','price_per_day'=>3800,'rating'=>8.9,'reviews'=>72,'badge'=>'Tech-Savvy','fuel_type'=>'Petrol','transmission'=>'Automatic','seats'=>5,'image'=>'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&q=80','is_active'=>1,'display_order'=>10],
];
seedTable($db, 'cars', $cars);

// ── BIKES ─────────────────────────────────────────────────────────────────────
$bikes = [
  ['name'=>'Bajaj Pulsar 220F','type'=>'Sports Bike','location'=>'Station Road, CSN','description'=>'High-performance sports bike for thrilling rides across the city and highways.','price_per_day'=>600,'rating'=>8.6,'reviews'=>134,'badge'=>'Popular','features'=>json_encode(['Disc Brakes','Alloy Wheels','Digital Meter']),'image'=>'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=800&q=80','is_active'=>1,'display_order'=>1],
  ['name'=>'Honda Activa 6G','type'=>'Scooter','location'=>'CIDCO, CSN','description'=>"India's most trusted scooter. Easy to ride, fuel-efficient, and perfect for daily city commuting.",'price_per_day'=>350,'rating'=>8.9,'reviews'=>210,'badge'=>'Bestseller','features'=>json_encode(['Front Disc Brake','Mobile Charging','LED']),'image'=>'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&q=80','is_active'=>1,'display_order'=>2],
  ['name'=>'Royal Enfield Classic 350','type'=>'Cruiser','location'=>'Padegaon, CSN','description'=>'Iconic cruiser for long-distance rides with timeless Royal Enfield retro style.','price_per_day'=>900,'rating'=>9.0,'reviews'=>88,'badge'=>'Flagship','features'=>json_encode(['Classic Design','Powerful Engine','Trip Meter']),'image'=>'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&q=80','is_active'=>1,'display_order'=>3],
  ['name'=>'Revolt RV400 (Electric)','type'=>'Electric Bike','location'=>'Garkheda, CSN','description'=>'Zero-emission electric bike. Eco-friendly, quiet, and perfect for city travel.','price_per_day'=>500,'rating'=>8.4,'reviews'=>62,'badge'=>'Eco-Friendly','features'=>json_encode(['AI Enabled','4 Riding Modes','150km Range']),'image'=>'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&q=80','is_active'=>1,'display_order'=>4],
  ['name'=>'TVS Apache RTR 160','type'=>'Sports Bike','location'=>'Kranti Chowk, CSN','description'=>'Sporty bike with race-tuned fuel injection. Perfect for enthusiasts.','price_per_day'=>550,'rating'=>8.5,'reviews'=>98,'badge'=>'','features'=>json_encode(['ABS','LED Headlamp','Digital Console']),'image'=>'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&q=80','is_active'=>1,'display_order'=>5],
  ['name'=>'Yamaha FZ-S V3','type'=>'Street Bike','location'=>'Jalna Road, CSN','description'=>'Muscular street bike with aggressive styling and smooth performance.','price_per_day'=>650,'rating'=>8.7,'reviews'=>76,'badge'=>'Stylish','features'=>json_encode(['LED Lights','Bluetooth','Single Channel ABS']),'image'=>'https://images.unsplash.com/photo-1449426468159-d96dbf08f19f?w=800&q=80','is_active'=>1,'display_order'=>6],
  ['name'=>'Hero Splendor Plus','type'=>'Commuter','location'=>'Osmanpura, CSN','description'=>'Most fuel-efficient bike. Perfect for daily commuting and budget travelers.','price_per_day'=>300,'rating'=>8.2,'reviews'=>189,'badge'=>'Budget','features'=>json_encode(['i3S Technology','Alloy Wheels','Tubeless Tyres']),'image'=>'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80','is_active'=>1,'display_order'=>7],
  ['name'=>'KTM Duke 200','type'=>'Naked Bike','location'=>'CIDCO, CSN','description'=>'Powerful naked street bike with aggressive performance and sharp handling.','price_per_day'=>1100,'rating'=>9.1,'reviews'=>54,'badge'=>'Performance','features'=>json_encode(['Liquid Cooled','ABS','TFT Display']),'image'=>'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800&q=80','is_active'=>1,'display_order'=>8],
  ['name'=>'Suzuki Access 125','type'=>'Scooter','location'=>'Garkheda, CSN','description'=>'Comfortable scooter with large under-seat storage. Great for city rides.','price_per_day'=>380,'rating'=>8.4,'reviews'=>142,'badge'=>'','features'=>json_encode(['LED Headlamp','USB Charger','Disc Brake']),'image'=>'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&q=80','is_active'=>1,'display_order'=>9],
  ['name'=>'Royal Enfield Himalayan','type'=>'Adventure','location'=>'Padegaon, CSN','description'=>'Adventure touring bike built for long rides and rough terrains.','price_per_day'=>1200,'rating'=>8.9,'reviews'=>67,'badge'=>'Adventure','features'=>json_encode(['Long Travel Suspension','Dual Purpose Tyres','Compass']),'image'=>'https://images.unsplash.com/photo-1609630875171-b1321377ee65?w=800&q=80','is_active'=>1,'display_order'=>10],
  ['name'=>'Electric City Bike','type'=>'Electric Bike','location'=>'Waluj, CSN','description'=>'Smooth and silent e-bike ideal for short city trips with zero carbon footprint.','price_per_day'=>450,'rating'=>8.1,'reviews'=>45,'badge'=>'','features'=>json_encode(['Pedal Assist','Long Range Battery']),'image'=>'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&q=80','is_active'=>1,'display_order'=>11],
  ['name'=>'Mountain Bike (Cycle)','type'=>'Bicycle','location'=>'Multiple Locations, CSN','description'=>'Eco-friendly mountain bicycle for exploring the city at your own pace.','price_per_day'=>150,'rating'=>7.9,'reviews'=>93,'badge'=>'Eco','features'=>json_encode(['21 Gears','Front Suspension','Water Bottle Holder']),'image'=>'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&q=80','is_active'=>1,'display_order'=>12],
];
seedTable($db, 'bikes', $bikes);

// ── RESTAURANTS ───────────────────────────────────────────────────────────────
$restaurants = [
  ['name'=>'Naivedya Thali Restaurant','type'=>'Traditional','cuisine'=>'Maharashtrian','location'=>'Nirala Bazaar, Chhatrapati Sambhajinagar','description'=>'The most authentic Maharashtrian Thali in the city. Unlimited servings of traditional dishes – a cultural experience on a plate.','price_per_person'=>350,'rating'=>9.0,'reviews'=>287,'badge'=>'Bestseller','image'=>'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80','is_active'=>1,'display_order'=>1],
  ['name'=>'Masala Dosa House','type'=>'South Indian','cuisine'=>'South Indian','location'=>'Samarth Nagar, CSN','description'=>'Famous for crispy masala dosas, idli, vada, and filter coffee. Authentic South Indian flavors.','price_per_person'=>200,'rating'=>8.7,'reviews'=>195,'badge'=>'Popular','image'=>'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&q=80','is_active'=>1,'display_order'=>2],
  ['name'=>'The Grill Room','type'=>'North Indian','cuisine'=>'North Indian, Mughlai','location'=>'Cantonment Area, CSN','description'=>'Indulge in rich Mughlai preparations, kebabs, biryanis, and North Indian curries in a royal ambiance.','price_per_person'=>600,'rating'=>8.5,'reviews'=>156,'badge'=>'','image'=>'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80','is_active'=>1,'display_order'=>3],
  ['name'=>'Chaat Street Corner','type'=>'Street Food','cuisine'=>'Street Food','location'=>'Gulmandi, CSN','description'=>'Vibrant street food stall serving the best Pani Puri, Bhel, Dahi Puri, and Sev Puri in town.','price_per_person'=>80,'rating'=>8.8,'reviews'=>412,'badge'=>'Local Favourite','image'=>'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&q=80','is_active'=>1,'display_order'=>4],
  ['name'=>'Renaissance Dine','type'=>'Multi-cuisine','cuisine'=>'Multi-cuisine, Continental','location'=>'CIDCO, Chhatrapati Sambhajinagar','description'=>'Fine dining with a wide variety of global and local cuisines. Premium experience with garden view seating.','price_per_person'=>900,'rating'=>9.1,'reviews'=>103,'badge'=>'Fine Dining','image'=>'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&q=80','is_active'=>1,'display_order'=>5],
  ['name'=>'Biryani Blues','type'=>'Biryani Specialist','cuisine'=>'Hyderabadi, Biryani','location'=>'Jalna Road, CSN','description'=>'Authentic Hyderabadi biryani with aromatic spices. Also serves kebabs and curries.','price_per_person'=>400,'rating'=>8.9,'reviews'=>234,'badge'=>'Biryani Special','image'=>'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&q=80','is_active'=>1,'display_order'=>6],
  ['name'=>'Pizza Paradise','type'=>'Italian','cuisine'=>'Italian, Pizza','location'=>'Samarth Nagar, CSN','description'=>'Wood-fired pizzas with fresh toppings. Also serves pasta and Italian appetizers.','price_per_person'=>450,'rating'=>8.3,'reviews'=>167,'badge'=>'','image'=>'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800&q=80','is_active'=>1,'display_order'=>7],
  ['name'=>'Chinese Wok','type'=>'Chinese','cuisine'=>'Chinese, Asian','location'=>'Kranti Chowk, CSN','description'=>'Authentic Chinese cuisine with Indo-Chinese favorites. Noodles, fried rice, and Manchurian specialties.','price_per_person'=>300,'rating'=>8.1,'reviews'=>189,'badge'=>'','image'=>'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80','is_active'=>1,'display_order'=>8],
  ['name'=>'Burger Junction','type'=>'Fast Food','cuisine'=>'American, Burgers','location'=>'Osmanpura, CSN','description'=>'Gourmet burgers with variety of patties and toppings. Also serves fries and shakes.','price_per_person'=>250,'rating'=>8.4,'reviews'=>298,'badge'=>'Quick Bites','image'=>'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80','is_active'=>1,'display_order'=>9],
  ['name'=>'Saffron Indian Kitchen','type'=>'Fine Dining','cuisine'=>'Indian, Multi-cuisine','location'=>'CIDCO, CSN','description'=>'Upscale restaurant with contemporary Indian cuisine. Live music on weekends.','price_per_person'=>800,'rating'=>8.8,'reviews'=>145,'badge'=>'Premium','image'=>'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80','is_active'=>1,'display_order'=>10],
  ['name'=>'Tandoor Nights','type'=>'Barbecue','cuisine'=>'North Indian, Tandoor','location'=>'Jalna Road, CSN','description'=>'Specializes in tandoori dishes. Kebabs, tikkas, and naan fresh from the clay oven.','price_per_person'=>500,'rating'=>8.6,'reviews'=>178,'badge'=>'Tandoor Special','image'=>'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80','is_active'=>1,'display_order'=>11],
  ['name'=>'Veg Delight','type'=>'Vegetarian','cuisine'=>'Pure Vegetarian','location'=>'Nirala Bazaar, CSN','description'=>'100% vegetarian restaurant with Jain food options. Healthy and hygienic.','price_per_person'=>280,'rating'=>8.5,'reviews'=>223,'badge'=>'Pure Veg','image'=>'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80','is_active'=>1,'display_order'=>12],
  ['name'=>'Dessert Paradise','type'=>'Dessert','cuisine'=>'Desserts, Sweets','location'=>'Samarth Nagar, CSN','description'=>'Heaven for sweet lovers. Ice creams, cakes, pastries, and traditional Indian sweets.','price_per_person'=>200,'rating'=>8.7,'reviews'=>312,'badge'=>'Sweet Tooth','image'=>'https://images.unsplash.com/photo-1551024601-bec78aea704b?w=800&q=80','is_active'=>1,'display_order'=>13],
];
seedTable($db, 'restaurants', $restaurants);

// ── ATTRACTIONS ───────────────────────────────────────────────────────────────
$attractions = [
  ['name'=>'Ajanta Caves','type'=>'UNESCO Heritage','location'=>'Ajanta, Maharashtra (105 km from CSN)','description'=>'Ancient Buddhist rock-cut cave monuments dating back to the 2nd century BCE. Famous for spectacular murals and sculptures. A UNESCO World Heritage Site.','entry_fee'=>40,'rating'=>9.5,'reviews'=>1820,'badge'=>'Must Visit','opening_hours'=>'9:00 AM – 5:30 PM (Closed Tuesdays)','best_time'=>'October to March','image'=>'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Kailash_Temple%2C_Ellora.jpg/800px-Kailash_Temple%2C_Ellora.jpg','is_active'=>1,'display_order'=>1],
  ['name'=>'Ellora Caves','type'=>'UNESCO Heritage','location'=>'Ellora, Maharashtra (30 km from CSN)','description'=>'A UNESCO World Heritage Site featuring 34 rock-cut caves representing Hindu, Buddhist, and Jain monuments from 600–1000 CE.','entry_fee'=>40,'rating'=>9.4,'reviews'=>2100,'badge'=>'Must Visit','opening_hours'=>'6:00 AM – 6:00 PM (Closed Tuesdays)','best_time'=>'October to March','image'=>'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80','is_active'=>1,'display_order'=>2],
  ['name'=>'Bibi Ka Maqbara','type'=>'Historical Monument','location'=>'Begumpura, Chhatrapati Sambhajinagar','description'=>'Known as the Taj of the Deccan, this beautiful 17th-century Mughal mausoleum was built by Prince Azam Shah in memory of his mother.','entry_fee'=>25,'rating'=>9.0,'reviews'=>945,'badge'=>'Iconic','opening_hours'=>'8:00 AM – 8:00 PM','best_time'=>'November to February','image'=>'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80','is_active'=>1,'display_order'=>3],
  ['name'=>'Daulatabad Fort','type'=>'Historical Fort','location'=>'Daulatabad, 15 km from CSN','description'=>'One of the strongest forts in India\'s history, built on a conical hill with a 180-degree moat and labyrinthine passages.','entry_fee'=>25,'rating'=>8.8,'reviews'=>678,'badge'=>'','opening_hours'=>'9:00 AM – 5:30 PM','best_time'=>'October to February','image'=>'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80','is_active'=>1,'display_order'=>4],
  ['name'=>'Panchakki (Water Mill)','type'=>'Heritage Site','location'=>'Dargah area, Chhatrapati Sambhajinagar','description'=>'A scenic 17th-century water mill powered by an underground stream. Part of the Sufi shrine complex, surrounded by beautiful gardens and a serene lake.','entry_fee'=>0,'rating'=>8.5,'reviews'=>534,'badge'=>'Free Entry','opening_hours'=>'6:00 AM – 10:00 PM','best_time'=>'All year','image'=>'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80','is_active'=>1,'display_order'=>5],
  ['name'=>'Grishneshwar Temple','type'=>'Religious Site','location'=>'Khuldabad, 30 km from CSN','description'=>'One of the 12 revered Jyotirlinga shrines of Lord Shiva in India. An important pilgrimage destination with ancient architecture.','entry_fee'=>0,'rating'=>9.2,'reviews'=>1100,'badge'=>'Pilgrimage','opening_hours'=>'5:30 AM – 9:30 PM','best_time'=>'All year','image'=>'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80','is_active'=>1,'display_order'=>6],
  ['name'=>'Salim Ali Lake & Bird Sanctuary','type'=>'Nature & Wildlife','location'=>'Near Delhi Gate, CSN','description'=>'Peaceful lake and bird sanctuary named after famous ornithologist. Perfect for bird watching and nature walks.','entry_fee'=>10,'rating'=>8.1,'reviews'=>287,'badge'=>'Nature','opening_hours'=>'6:00 AM – 6:00 PM','best_time'=>'November to February','image'=>'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80','is_active'=>1,'display_order'=>7],
  ['name'=>'Siddharth Garden & Zoo','type'=>'Garden & Zoo','location'=>'Jalna Road, CSN','description'=>'Large garden with zoo, toy train, and boating facilities. Great for family outings.','entry_fee'=>20,'rating'=>7.9,'reviews'=>456,'badge'=>'Family Fun','opening_hours'=>'9:00 AM – 6:00 PM','best_time'=>'All year','image'=>'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&q=80','is_active'=>1,'display_order'=>8],
  ['name'=>'Aurangabad Caves','type'=>'Historical Caves','location'=>'Near Bibi Ka Maqbara, CSN','description'=>'12 rock-cut Buddhist shrines dating from 3rd to 7th century. Less crowded alternative to Ajanta-Ellora.','entry_fee'=>15,'rating'=>8.3,'reviews'=>198,'badge'=>'','opening_hours'=>'9:00 AM – 5:30 PM (Closed Mondays)','best_time'=>'October to March','image'=>'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80','is_active'=>1,'display_order'=>9],
  ['name'=>'Khuldabad (Valley of Saints)','type'=>'Religious & Historical','location'=>'Khuldabad, 30 km from CSN','description'=>'Historic town with tombs of Mughal emperor Aurangzeb and Sufi saints. Peaceful spiritual atmosphere.','entry_fee'=>0,'rating'=>8.4,'reviews'=>234,'badge'=>'Heritage','opening_hours'=>'Sunrise to Sunset','best_time'=>'October to March','image'=>'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80','is_active'=>1,'display_order'=>10],
  ['name'=>'Bhadra Maruti Temple','type'=>'Religious Site','location'=>'Khuldabad, 30 km from CSN','description'=>'Unique temple with reclining Hanuman idol. One of the few temples where Hanuman is in sleeping posture.','entry_fee'=>0,'rating'=>8.6,'reviews'=>167,'badge'=>'Unique','opening_hours'=>'5:00 AM – 9:00 PM','best_time'=>'All year','image'=>'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80','is_active'=>1,'display_order'=>11],
  ['name'=>'Himayat Bagh','type'=>'Garden','location'=>'Near Railway Station, CSN','description'=>'Historic Mughal garden with beautiful landscaping. Perfect for morning walks and picnics.','entry_fee'=>5,'rating'=>7.8,'reviews'=>312,'badge'=>'','opening_hours'=>'6:00 AM – 8:00 PM','best_time'=>'October to March','image'=>'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80','is_active'=>1,'display_order'=>12],
  ['name'=>'Chhatrapati Sambhaji Maharaj Museum','type'=>'Museum','location'=>'Near Bibi Ka Maqbara, CSN','description'=>'Museum showcasing history and culture of Marathwada region. Artifacts, sculptures, and paintings.','entry_fee'=>10,'rating'=>8.0,'reviews'=>145,'badge'=>'Educational','opening_hours'=>'10:00 AM – 5:00 PM (Closed Mondays)','best_time'=>'All year','image'=>'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80','is_active'=>1,'display_order'=>13],
  ['name'=>'Soneri Mahal (Golden Palace)','type'=>'Historical Palace','location'=>'Near Panchakki, CSN','description'=>'17th-century palace with beautiful paintings and architecture. Now houses a museum.','entry_fee'=>15,'rating'=>8.1,'reviews'=>123,'badge'=>'','opening_hours'=>'9:00 AM – 5:00 PM','best_time'=>'October to March','image'=>'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80','is_active'=>1,'display_order'=>14],
];
seedTable($db, 'attractions', $attractions);

// ── BUSES ─────────────────────────────────────────────────────────────────────
$buses = [
  ['operator'=>'MSRTC Shivneri Express','bus_type'=>'AC Semi-Luxury','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Pune','departure_time'=>'06:00 AM','duration'=>'4h 30m','price'=>350,'rating'=>8.5,'reviews'=>310,'badge'=>'Fastest Route','amenities'=>json_encode(['AC','Charging Points','Water Bottle']),'image'=>'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80','is_active'=>1,'display_order'=>1],
  ['operator'=>'Dolphin Travels Night Bus','bus_type'=>'AC Sleeper','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Mumbai','departure_time'=>'10:30 PM','duration'=>'7h 15m','price'=>650,'rating'=>8.1,'reviews'=>198,'badge'=>'','amenities'=>json_encode(['AC','Sleeper Berths','Blanket']),'image'=>'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&q=80','is_active'=>1,'display_order'=>2],
  ['operator'=>'Hans Travels AC Sleeper','bus_type'=>'AC Sleeper','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Nagpur','departure_time'=>'09:00 PM','duration'=>'8h 45m','price'=>580,'rating'=>8.3,'reviews'=>145,'badge'=>'AC Sleeper','amenities'=>json_encode(['AC','Sleeper Berths','Charging Points']),'image'=>'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80','is_active'=>1,'display_order'=>3],
  ['operator'=>'Purple Travels Volvo','bus_type'=>'Volvo AC','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Nashik','departure_time'=>'05:30 AM','duration'=>'5h 00m','price'=>420,'rating'=>8.7,'reviews'=>88,'badge'=>'Comfortable','amenities'=>json_encode(['AC','Reclining Seats','Entertainment']),'image'=>'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&q=80','is_active'=>1,'display_order'=>4],
  ['operator'=>'MSRTC Shivshahi','bus_type'=>'AC Seater','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Shirdi','departure_time'=>'07:00 AM','duration'=>'3h 30m','price'=>280,'rating'=>8.4,'reviews'=>234,'badge'=>'Pilgrimage','amenities'=>json_encode(['AC','Charging Points']),'image'=>'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80','is_active'=>1,'display_order'=>5],
  ['operator'=>'VRL Travels','bus_type'=>'AC Sleeper','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Bangalore','departure_time'=>'05:00 PM','duration'=>'14h 30m','price'=>1200,'rating'=>8.6,'reviews'=>167,'badge'=>'Long Distance','amenities'=>json_encode(['AC','Sleeper Berths','Blanket','Charging Points']),'image'=>'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&q=80','is_active'=>1,'display_order'=>6],
  ['operator'=>'Orange Travels','bus_type'=>'AC Sleeper','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Hyderabad','departure_time'=>'08:30 PM','duration'=>'10h 00m','price'=>850,'rating'=>8.2,'reviews'=>189,'badge'=>'','amenities'=>json_encode(['AC','Sleeper Berths']),'image'=>'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80','is_active'=>1,'display_order'=>7],
  ['operator'=>'MSRTC Hirkani','bus_type'=>'AC Semi-Luxury','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Kolhapur','departure_time'=>'06:30 AM','duration'=>'6h 30m','price'=>450,'rating'=>8.1,'reviews'=>123,'badge'=>'','amenities'=>json_encode(['AC','Charging Points']),'image'=>'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&q=80','is_active'=>1,'display_order'=>8],
  ['operator'=>'Neeta Travels','bus_type'=>'AC Sleeper','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Goa','departure_time'=>'04:00 PM','duration'=>'12h 00m','price'=>1100,'rating'=>8.5,'reviews'=>198,'badge'=>'Beach Route','amenities'=>json_encode(['AC','Sleeper Berths','Blanket']),'image'=>'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80','is_active'=>1,'display_order'=>9],
  ['operator'=>'MSRTC Parivartan','bus_type'=>'Non-AC Seater','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Ajanta Caves','departure_time'=>'08:00 AM','duration'=>'2h 30m','price'=>120,'rating'=>7.9,'reviews'=>267,'badge'=>'Budget','amenities'=>json_encode(['Non-AC']),'image'=>'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80','is_active'=>1,'display_order'=>10],
  ['operator'=>'Sharma Travels','bus_type'=>'AC Sleeper','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Indore','departure_time'=>'07:00 PM','duration'=>'9h 30m','price'=>750,'rating'=>8.0,'reviews'=>145,'badge'=>'','amenities'=>json_encode(['AC','Sleeper Berths']),'image'=>'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=800&q=80','is_active'=>1,'display_order'=>11],
  ['operator'=>'MSRTC Ashwamedh','bus_type'=>'AC Seater','from_location'=>'Chhatrapati Sambhajinagar','to_location'=>'Solapur','departure_time'=>'09:30 AM','duration'=>'4h 00m','price'=>320,'rating'=>8.2,'reviews'=>178,'badge'=>'','amenities'=>json_encode(['AC','Charging Points']),'image'=>'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=800&q=80','is_active'=>1,'display_order'=>12],
];
seedTable($db, 'buses', $buses);

echo "\nAll done! Visit your site to see real listings.\n";
if (php_sapi_name() !== 'cli') {
    echo '<br><a href="../listing.php?type=stays">View Stays</a>';
}
